-- Supabase schema required by AI Job Matching production persistence.
-- Run this once in Supabase SQL Editor before deploying the Render backend.

create table if not exists public.user_data (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_jobs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id text not null,
  is_final boolean not null default false,
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, job_id, is_final)
);

create index if not exists user_jobs_user_id_is_final_idx
  on public.user_jobs (user_id, is_final);

create index if not exists user_jobs_data_gin_idx
  on public.user_jobs using gin (data);

alter table public.user_data enable row level security;
alter table public.user_jobs enable row level security;

drop policy if exists "Users can read own AI matching profile" on public.user_data;
create policy "Users can read own AI matching profile"
  on public.user_data for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own AI matching profile" on public.user_data;
create policy "Users can insert own AI matching profile"
  on public.user_data for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own AI matching profile" on public.user_data;
create policy "Users can update own AI matching profile"
  on public.user_data for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own AI matching profile" on public.user_data;
create policy "Users can delete own AI matching profile"
  on public.user_data for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read own AI matching jobs" on public.user_jobs;
create policy "Users can read own AI matching jobs"
  on public.user_jobs for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own AI matching jobs" on public.user_jobs;
create policy "Users can insert own AI matching jobs"
  on public.user_jobs for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own AI matching jobs" on public.user_jobs;
create policy "Users can update own AI matching jobs"
  on public.user_jobs for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own AI matching jobs" on public.user_jobs;
create policy "Users can delete own AI matching jobs"
  on public.user_jobs for delete
  using (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_user_data_updated_at on public.user_data;
create trigger set_user_data_updated_at
  before update on public.user_data
  for each row execute function public.set_updated_at();

drop trigger if exists set_user_jobs_updated_at on public.user_jobs;
create trigger set_user_jobs_updated_at
  before update on public.user_jobs
  for each row execute function public.set_updated_at();
